version: '3'
services:
  digdag_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "65432:65432"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: digdag_db
      POSTGRES_USER: digdag
      POSTGRES_PASSWORD: digdag
    volumes:
      - .:/src
    command: /bin/bash bin/digdag
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: digdag_db
      POSTGRES_USER: digdag
      POSTGRES_PASSWORD: digdag
